# Generated by Django 6.0 on 2026-03-17 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_complaint_authority_complaint_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityComplaint',
            fields=[
            ],
            options={
                'verbose_name': 'Electricity Complaint',
                'verbose_name_plural': 'Electricity Complaints',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('complaint.complaint',),
        ),
        migrations.CreateModel(
            name='GarbageComplaint',
            fields=[
            ],
            options={
                'verbose_name': 'Garbage Complaint',
                'verbose_name_plural': 'Garbage Complaints',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('complaint.complaint',),
        ),
        migrations.CreateModel(
            name='RoadComplaint',
            fields=[
            ],
            options={
                'verbose_name': 'Road Complaint',
                'verbose_name_plural': 'Road Complaints',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('complaint.complaint',),
        ),
        migrations.CreateModel(
            name='WaterComplaint',
            fields=[
            ],
            options={
                'verbose_name': 'Water Complaint',
                'verbose_name_plural': 'Water Complaints',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('complaint.complaint',),
        ),
    ]
