# Generated by Django 6.0 on 2026-03-17 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_alter_complaint_category_alter_complaint_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricitycomplaint',
            options={'verbose_name_plural': 'Electricity Complaints'},
        ),
        migrations.AlterModelOptions(
            name='garbagecomplaint',
            options={'verbose_name_plural': 'Garbage Complaints'},
        ),
        migrations.AlterModelOptions(
            name='roadcomplaint',
            options={'verbose_name_plural': 'Road Complaints'},
        ),
        migrations.AlterModelOptions(
            name='watercomplaint',
            options={'verbose_name_plural': 'Water Complaints'},
        ),
    ]
