# Generated by Django 5.1.5 on 2026-03-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_alter_complaint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='citizen_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
