# Generated by Django 6.0 on 2026-03-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0010_alter_complaint_authority_alter_complaint_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ml_status',
            field=models.CharField(default='UNCERTAIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='authority',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='citizen_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='citizen_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='citizen_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='citizen_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
