# Generated by Django 6.0 on 2026-03-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0011_complaint_ml_status_alter_complaint_authority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='citizen_email',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='citizen_location',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='citizen_name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='citizen_phone',
        ),
    ]
