# Generated by Django 6.0 on 2026-03-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0012_remove_complaint_citizen_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='citizen_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
