# Generated by Django 6.0 on 2026-03-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0013_complaint_citizen_email_complaint_citizen_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='citizen_email',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='citizen_location',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='citizen_name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='citizen_phone',
        ),
    ]
